export const CURATED_CORPUS = [
  ["sebi", "SEBI and investor protection", "SEBI", "SEBI is India's securities-market regulator. Investors can use official SEBI investor education resources to understand regulated market intermediaries, disclosures, grievance routes, and the risks of market-linked products. This internally authored summary is not an official SEBI publication and does not recommend a security."],
  ["budgeting", "Budgeting basics", "budgeting", "A budget organizes expected income and spending over a period. Tracking essential and discretionary expenses can make recurring commitments visible and help compare planned spending with actual cash flow. Review a budget when income or expenses change."],
  ["emergency-fund", "Emergency fund basics", "emergency fund", "An emergency reserve is liquid savings set aside for unexpected expenses or income disruption. The appropriate amount depends on household obligations, income stability, insurance, and access to other resources; no single target fits everyone."],
  ["debt", "Debt and repayment choices", "debt", "Debt creates contractual repayment obligations and may include interest, fees, and penalties. Compare the terms, rates, minimum payments, and consequences before changing repayment priorities. Avoid taking on obligations that cannot be supported by the household cash-flow plan."],
  ["liquidity", "Liquidity and access to cash", "liquidity", "Liquidity describes how readily an asset can be converted to spendable cash without a material loss or delay. Cash needs, withdrawal restrictions, settlement time, and price variability matter when matching resources to near-term obligations."],
  ["risk", "Understanding financial risk", "risk", "Risk is uncertainty about outcomes, including loss, delay, or inability to meet an obligation. Consider both the likelihood and impact of adverse outcomes, time horizon, liquidity needs, and capacity to absorb loss. Historical outcomes do not guarantee future results."],
  ["diversification", "Diversification basics", "diversification", "Diversification spreads exposure across different assets or sources of risk. It may reduce the effect of a concentrated exposure, but it cannot eliminate market risk or guarantee a profit. Correlations and exposures can change over time."],
  ["financial-goals", "Planning financial goals", "financial goals", "A financial goal identifies an intended use, target amount, and time horizon. Compare current resources and planned contributions with the goal, while recognizing that future costs, income, and investment outcomes may be uncertain. Revisit priorities as circumstances change."],
] as const;

export const CORPUS_SOURCE_ID = "f444f4a4-5a1d-4b7f-8efb-6ec0727b6a17";
